# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-22 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Тур', 'verbose_name_plural': 'Туры'},
        ),
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='tour',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Место'),
        ),
        migrations.AddField(
            model_name='tour',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата конца'),
        ),
        migrations.AddField(
            model_name='tour',
            name='hotel',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Отель/гостиница'),
        ),
        migrations.AddField(
            model_name='tour',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название'),
        ),
    ]
