# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-22 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20160522_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bgimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Фоновые изображения',
                'verbose_name': 'Фоновое изображение',
            },
        ),
    ]
