# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-28 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_bgimg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-id'], 'verbose_name': 'Тур', 'verbose_name_plural': 'Туры'},
        ),
    ]
