# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-28 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20160528_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст цитаты')),
            ],
            options={
                'verbose_name': 'Случайная цитата',
                'verbose_name_plural': 'Случайные цитаты',
            },
        ),
    ]
