# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-28 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_auto_20160529_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='parent',
            new_name='parent_user',
        ),
        migrations.AddField(
            model_name='app',
            name='parent_tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.Tour'),
        ),
    ]
