# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 10:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0009_auto_20160529_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='parent',
            new_name='parent_tour',
        ),
        migrations.AddField(
            model_name='review',
            name='parent_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
