# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_auto_20160529_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodimage',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Good',
        ),
        migrations.DeleteModel(
            name='GoodImage',
        ),
    ]
