# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_auto_20160529_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='addres',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес улицы/дома'),
        ),
        migrations.AddField(
            model_name='app',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='app',
            name='district',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='app',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='app',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Контактный телефон'),
        ),
        migrations.AddField(
            model_name='app',
            name='town',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Город'),
        ),
    ]
