# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_auto_20160530_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='country',
            field=models.CharField(blank=True, choices=[('Россия', 'Россия'), ('Белоруссияя', 'Белоруссия'), ('Азербайджан', 'Азербайджан'), ('Казахстан', 'Казахстан'), ('Армения', 'Армения')], max_length=200, null=True, verbose_name='Страна'),
        ),
    ]
