# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0015_auto_20160530_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='E-mail'),
        ),
    ]
