# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0017_auto_20160530_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='addres',
            field=models.CharField(max_length=200, null=True, verbose_name='Адрес улицы/дома'),
        ),
        migrations.AlterField(
            model_name='app',
            name='country',
            field=models.CharField(choices=[('Россия', 'Россия'), ('Белоруссияя', 'Белоруссия'), ('Азербайджан', 'Азербайджан'), ('Казахстан', 'Казахстан'), ('Армения', 'Армения')], max_length=200, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='app',
            name='district',
            field=models.CharField(max_length=200, null=True, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='app',
            name='town',
            field=models.CharField(max_length=200, null=True, verbose_name='Город'),
        ),
    ]
