# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0020_auto_20160530_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='hotel_addres',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес отеля'),
        ),
        migrations.AddField(
            model_name='room',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.Tour'),
        ),
    ]
