# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0021_auto_20160530_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cost',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание'),
        ),
    ]
