# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20160529_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='warhouse',
            field=models.IntegerField(blank=True, null=True, verbose_name='Наличие'),
        ),
    ]
